module.exports = {
    RedisIdPairToMap: require('./lib/collection/RedisIdPairToMap'),
    RedisIdToMap: require('./lib/collection/RedisIdToMap'),
    RedisIdToSet: require('./lib/collection/RedisIdToSet'),
    RedisIdToSortedSet: require('./lib/collection/RedisIdToSortedSet'),
    RedisIdPairToSortedSet: require('./lib/collection/RedisIdPairToSortedSet'),
    RedisIdsToSortedSet: require('./lib/collection/RedisIdsToSortedSet'),
    RedisIdToValue: require('./lib/collection/RedisIdToValue'),
    RedisIdPairToValue: require('./lib/collection/RedisIdPairToValue'),
    RedisMap: require('./lib/collection/RedisMap'),
    RedisSet: require('./lib/collection/RedisSet'),
    RedisList: require('./lib/collection/RedisList'),
    RedisSortedSet: require('./lib/collection/RedisSortedSet'),
    Store: require('./lib/Store'),
    Mock: {
        RedisIdPairToMap: require('./lib/mock/MockIdPairToMap'),
        RedisIdToMap: require('./lib/mock/MockIdToMap'),
        RedisIdToSet: require('./lib/mock/MockIdToSet'),
        RedisIdToSortedSet: require('./lib/mock/MockIdToSortedSet'),
        RedisIdPairToSortedSet: require('./lib/mock/MockIdPairToSortedSet'),
        RedisIdsToSortedSet: require('./lib/mock/MockIdsToSortedSet'),
        RedisIdToValue: require('./lib/mock/MockIdToValue'),
        RedisIdPairToValue: require('./lib/mock/MockIdPairToValue'),
        RedisMap: require('./lib/mock/MockMap'),
        RedisSet: require('./lib/mock/MockSet'),
        RedisList: require('./lib/mock/MockList'),
        RedisSortedSet: require('./lib/mock/MockSortedSet'),
        Store: require('./lib/mock/MockStore'),
    }
}